--- 
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG 
  hosts: routers 
  gather_facts: false 
  connection: local 
  
  tasks: 
   - name: DISPLAYING THE RUNNING-CONFIG 
     ios_command: 
       commands: 
         - show running-config   
     register: config 
  
   - name: SAVE OUTPUT TO ./ansible-data/backups/ 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "ansible-data/backups/backup_config_{{ inventory_hostname }}.txt"